#!/bin/bash
cd $(dirname $0)/..
#git branch gh-pages
#git checkout gh-pages
fpm run prep -- --help  > docs/prep.1.man
txt2man \
 -P pname -t 'Fortran preprocessor' -r 8.1.1 -s 1 -v 'User Commands' \
 -B 'BLOCK' -B 'DEFINE' -B 'ELIF' -B 'ELSE' -B 'ELSEIF' -B 'ENDBLOCK' \
 -B 'ENDIF' -B 'ENDPARCEL' -B 'ERROR' -B 'IDENT' -B 'IF' -B 'IFDEF' -B 'IFNDEF' \
 -B 'IMPORT' -B 'INCLUDE' -B 'MESSAGE' -B '{NAME}' -B 'OUTPUT' -B 'PARCEL' -B 'POST' \
 -B 'PREP_DOCUMENT_DIR' -B 'QUIT' -B 'REDEFINE' -B 'SET' \
 -B 'SHOW' -B 'stop' -B 'STOP'  -B 'SYSTEM' -B 'UNDEF' -B 'UNDEFINE' \
 docs/prep.1.man > docs/prep.1
man2html docs/prep.1    > docs/prep.1.html
cp docs/prep.1.html /tmp/
#git checkout main
cygstart /tmp/prep.1.html
exit
