#!/bin/sh
#@(#) run Markdown.pl on a text file to convert it to HTML
################################################################################
# parse command line
eval $(parse MD -help NO -noheader NO -nofooter NO)
eval $(parse MD ${*})
################################################################################
# md -help|md |w3m -dump -T text/html|more
################################################################################
header(){
cat <<EOF
<html>
<head>
<title>$FILENAME</title>
<style>
body {xfont-style: italic}
body {
background-color:#FFF; color:#333; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:1em; line-height:1.3em; }
a:visited { color:#666; }
h1,h2,h3,h4,h5,h6 { color:#333; font-family:georgia, verdana, sans-serif; }
h1 { font-size:200%; }
h2 { font-size:173%; }
h3 { font-size:144%; }
h4 { font-size:120%; }
h5,h6 { font-size:100% }
a.nav,a:link.nav, a:visited.nav { background-color:#FFF; color:#000; }
table { border:double #000; border-collapse:collapse; }
td { border:thin solid #888; }
li { margin-bottom:0.5em; }
blockquote { display:block; font-size:90%; font-style:italic; line-height:1.5em; margin:0 0 1.5em; padding:0 2.5em; }
pre { background-color:#DDD; font-size:90%; overflow:auto; padding:1em; }
a,li span { color:#000; }
a:hover, a.nav:hover, a:hover math { background-color:#000; color:#FFF; }
#Container { margin:0 10px; text-align:center; }
#Content { border-top:none; margin:auto; padding:0.3em; text-align:left; width:100%; max-width:55em; }
span.webName { font-size:.5em; }
textarea#content { font-size: 1em; line-height: 1.125em; }
h1#pageName { line-height:1.4em; margin:0.2em 0 0.2em 0; padding:0; }
h2{ line-height:1.2em; margin:0.2em 0 0.2em 0; padding:0; color:blue;}
.property { color:#666; font-size:80%; }
a.existingWikiWord[title]{ //border: 1px dashed #BBB; }
.byline { color:#666; font-size:.8em; font-style:italic; margin-bottom:1em; padding-top:1px; }
</style>
</head>
<body>
<div id="Container">
<div id="Content">
EOF
}
################################################################################
footer(){
cat <<EOF
<p><div class='property'> category: <a class='category_link' href='/fortran/list/code'>code</a></div></p>
  <div class="byline">
  Revised on $(date)
  by
  <a class="existingWikiWord" href="${USER:-$LOGNAME}.xhtml">${USER:-$LOGNAME}</a>
  </div>
  </div>
 </div>
</body>
</html>
EOF
}
################################################################################
case "$MD_help" in
NO) 
   [ "$MD_noheader" = NO ] && header
   #$(dirname $0)/Markdown_1.0.1/Markdown.pl $MD_00
   ${0%/*}/Markdown_1.0.1/Markdown.pl $MD_00
   [ "$MD_nofooter" = NO ] && footer
;;
*) 
   #more $(dirname $0)/Markdown_1.0.1/syntax.txt
   more ${0%/*}/Markdown_1.0.1/syntax.txt
;;
esac
################################################################################
exit
################################################################################
